//! Lorca's Device core, and, with the `runner` feature, the Runner: keys, the relay sync,
//! jobs and rooms, questions to other Runners, and the JSON API the apps speak. The `lorca`
//! binary adds the local websocket server and the command line; the phone links the core
//! alone through `lorca-mobile`.

pub mod api;
pub mod app;
pub mod budgets;
pub mod browser;
pub mod catalog;
pub mod config;
#[cfg(feature = "runner")]
pub mod connector_limits;
pub mod credentials;
pub mod crypto;
#[cfg(feature = "runner")]
pub mod decisions;
pub mod events;
pub mod files;
pub mod handoffs;
pub mod identity;
pub mod keys;
#[cfg(feature = "runner")]
pub mod local_review;
pub mod marketplace;
pub mod memory;
pub mod model;
pub mod outputs;
pub mod pairing;
pub mod permissions;
pub mod plugins;
#[cfg(feature = "provider-auth")]
pub mod provider_auth;
#[cfg(feature = "runner")]
pub mod providers;
pub mod push;
pub mod relay;
pub mod requests;
pub mod review_queue;
#[cfg(feature = "runner")]
pub mod review_execution;
pub mod routines;
pub mod routine_health;
pub mod runtime;
pub mod schedule;
#[cfg(feature = "runner")]
pub mod scripts;
pub mod served;
#[cfg(feature = "cli")]
pub mod service;
#[cfg(feature = "runner")]
pub mod shell;
pub mod sync;
pub mod tasks;
pub mod local_store;
#[cfg(feature = "runner")]
pub mod turns;
#[cfg(feature = "cli")]
pub mod update;
#[cfg(feature = "server")]
pub mod ws;
