/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as ZhLlmsFullDottxtRouteImport } from './routes/zh_/llms-full[.]txt'
import { Route as ZhLlmsDottxtRouteImport } from './routes/zh_/llms[.]txt'
import { Route as ZhDocsSplatRouteImport } from './routes/zh_/docs/$'
import { Route as ZhDocsChar123Char125DotmdRouteImport } from './routes/zh_/docs/{$}[.]md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLlmsFullDottxtRoute = ZhLlmsFullDottxtRouteImport.update({
  id: '/zh_/llms-full.txt',
  path: '/zh/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLlmsDottxtRoute = ZhLlmsDottxtRouteImport.update({
  id: '/zh_/llms.txt',
  path: '/zh/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDocsSplatRoute = ZhDocsSplatRouteImport.update({
  id: '/zh_/docs/$',
  path: '/zh/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDocsChar123Char125DotmdRoute =
  ZhDocsChar123Char125DotmdRouteImport.update({
    id: '/zh_/docs/{$}.md',
    path: '/zh/docs/{$}.md',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/zh': typeof ZhRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/zh/llms-full.txt': typeof ZhLlmsFullDottxtRoute
  '/zh/llms.txt': typeof ZhLlmsDottxtRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/zh/docs/{$}.md': typeof ZhDocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/zh': typeof ZhRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/zh/llms-full.txt': typeof ZhLlmsFullDottxtRoute
  '/zh/llms.txt': typeof ZhLlmsDottxtRoute
  '/zh/docs/$': typeof ZhDocsSplatRoute
  '/zh/docs/{$}.md': typeof ZhDocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/zh': typeof ZhRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/zh_/llms-full.txt': typeof ZhLlmsFullDottxtRoute
  '/zh_/llms.txt': typeof ZhLlmsDottxtRoute
  '/zh_/docs/$': typeof ZhDocsSplatRoute
  '/zh_/docs/{$}.md': typeof ZhDocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/zh'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/zh/llms-full.txt'
    | '/zh/llms.txt'
    | '/zh/docs/$'
    | '/zh/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/zh'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/zh/llms-full.txt'
    | '/zh/llms.txt'
    | '/zh/docs/$'
    | '/zh/docs/{$}.md'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/zh'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/zh_/llms-full.txt'
    | '/zh_/llms.txt'
    | '/zh_/docs/$'
    | '/zh_/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ZhRoute: typeof ZhRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  ZhLlmsFullDottxtRoute: typeof ZhLlmsFullDottxtRoute
  ZhLlmsDottxtRoute: typeof ZhLlmsDottxtRoute
  ZhDocsSplatRoute: typeof ZhDocsSplatRoute
  ZhDocsChar123Char125DotmdRoute: typeof ZhDocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh_/llms-full.txt': {
      id: '/zh_/llms-full.txt'
      path: '/zh/llms-full.txt'
      fullPath: '/zh/llms-full.txt'
      preLoaderRoute: typeof ZhLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh_/llms.txt': {
      id: '/zh_/llms.txt'
      path: '/zh/llms.txt'
      fullPath: '/zh/llms.txt'
      preLoaderRoute: typeof ZhLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh_/docs/$': {
      id: '/zh_/docs/$'
      path: '/zh/docs/$'
      fullPath: '/zh/docs/$'
      preLoaderRoute: typeof ZhDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh_/docs/{$}.md': {
      id: '/zh_/docs/{$}.md'
      path: '/zh/docs/{$}.md'
      fullPath: '/zh/docs/{$}.md'
      preLoaderRoute: typeof ZhDocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ZhRoute: ZhRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  ZhLlmsFullDottxtRoute: ZhLlmsFullDottxtRoute,
  ZhLlmsDottxtRoute: ZhLlmsDottxtRoute,
  ZhDocsSplatRoute: ZhDocsSplatRoute,
  ZhDocsChar123Char125DotmdRoute: ZhDocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
